services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rag-backend
    env_file: ./backend/.env
    ports:
      - "8000:8000"
    command: uvicorn api:app --host 0.0.0.0 --port 8000
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # CRA reads this at BUILD TIME to bake the API URL into the bundle
        REACT_APP_API_URL: "http://localhost:8000"
    container_name: rag-frontend
    ports:
      # Nginx in the image listens on 8080; map it to 3000 locally
      - "3000:8080"
    depends_on:
      - backend
    restart: unless-stopped
